!!config.CliConfiguration
run:
  tasks:
    - watch
  args:
    path: /from/
anidb:
  cache:
    fileName: aniAdd.sqlite
    ttlInDays: 30
move:
  deleteEmptyDirs: true
  duplicates:
    folder: /duplicates/
  mode: TAGSYSTEM
  unknown:
    folder: /unknown/
mylist:
  add: true
  overwrite: false
  storageType: REMOTE
  watched: false
paths:
  movieFolders:
  - path: /movies/
    tagSystemName: BaseMoviePath
  tvShowFolders:
  - path: /shows/
    tagSystemName: BaseTVShowPath
rename:
  related: true
  mode: TAGSYSTEM
tagSystem: |-
  # Names anime in the following format "ShowTitle S01EXX EpisodeTitle [Group][Source][Resolution][Codec][CRC]""
  # Kodi should parse those episode numbers correctly
  # Contains anime with names that kodi anidb info provider cannot handle: 86
  ForceEnglishNames:=",15441," # Comma delimited list of anime IDs to force English names, start and end with , (=SEP)
  SEP:=","
  # Use Romanized show title for all except the anime in the list above
  ShowTitle:={$indexof(%ForceEnglishNames%, %SEP% %AId% %SEP%) = "-1" ? [%ATr%, %ATe%, %ATk%] : [%ATe%, %ATr%, %ATk%]}
  EpisodeTitle:=[%ETe%, %ETr%, %ETk%]
  ShowTitle:=$repl(%ShowTitle%, "\?|\s*\.+$", "_")
  ShowTitle:=$repl(%ShowTitle%, '[\\":/*|<>?]', " ")
  EpisodeTitle:=$repl(%EpisodeTitle%, '[\\":/*|<>?]', " ")
  ShowTitle:=$repl(%ShowTitle%, "\s+", " ")
  EpisodeTitle:=$repl(%EpisodeTitle%, "\s+", " ")
  ShowTitle:=$repl(%ShowTitle%, "^\s|\s$", "")
  EpisodeTitle:=$repl(%EpisodeTitle%, "^\s|\s$", "")
  ShowTitle:=$repl(%ShowTitle%, "`", "'")
  EpisodeTitle:=$repl(%EpisodeTitle%, "`", "'")
  Trunc(str, len):=$repl(%str%, ".{" $len($repl(%str%, "(.?){" %len% "}$", "")) "}$", "")
  TruncEllipse(str, len):={$len(%str%) = $len($Trunc(%str%, %len%)) ? %str% : $Trunc(%str%, %len%) "…" }
  EpisodeTitle:=$TruncEllipse(%EpisodeTitle%, "64")
  Regular:="S01E"
  Special:="S00E"
  Separator:=" "
  SpecialEp:=$repl(%EpNo%, "[1234567890]", "")
  EpNo:=$repl(%EpNo%, "[SCTPO]", "")
  Ver:={%Ver% = "1" ? "" : "v" %Ver% }
  Pad:={%SpecialEp% ? "2" : $max($len(%EpHiNo%), $len(%EpCount%)) }
  Pad:={$match(%EpCount%, "0") ? $max("2", %Pad%) : %Pad% }
  EpNoPad:=$pad(%EpNo%, %Pad%, "0")
  EpNoPad:={%SpecialEp%       ? %EpNoPad%  :  %Regular%   %EpNoPad% }
  EpNoPad:={%SpecialEp% = "S" ? %Special%     %EpNoPad% : %EpNoPad% }
  EpNoPad:={%SpecialEp% = "C" ? %Special% "1" %EpNoPad% : %EpNoPad% }
  EpNoPad:={%SpecialEp% = "T" ? %Special% "2" %EpNoPad% : %EpNoPad% }
  EpNoPad:={%SpecialEp% = "P" ? %Special% "3" %EpNoPad% : %EpNoPad% }
  EpNoPad:={%SpecialEp% = "O" ? %Special% "4" %EpNoPad% : %EpNoPad% }
  EpNoFull:=%Separator% %EpNoPad% %Ver% %Separator%
  GT:="[" [%GTs%, %GTl%] "]"
  Src:="[" $repl(%Source%, "B-R|Blu-ray", "BluRay") "]"
  Cen:={%Cen% ? "[Cen]" : "" }
  Res:="[" %FVideoRes% "]"
  VCodec:="[" $repl(%FVCodec%,"H264/AVC","h264") "]"
  ACodec:="[" %FACodec% "]"
  CRC:="[" $uc(%FCrc%) "]"
  FileInfo:=" " %GT% %Src% %Cen% %Res% %VCodec% %CRC%
  MovieTypes:="Movie|OVA"
  IsMovie:={$match(%Type%, %MovieTypes%) ? {%EpCount% = "1" ? {%SpecialEp% ? "" : "1" } : "" } : "" }
  MovieFileName:=%ShowTitle% %FileInfo%
  TVShowFileName:=%ShowTitle% %EpNoFull% %EpisodeTitle% %FileInfo%
  BasePath:={%IsMovie% ? %BaseMoviePath% : %BaseTVShowPath% }
  FileName:={%IsMovie% ? %MovieFileName% : %TVShowFileName% }
  PathName:=%BasePath% %ShowTitle%
